steps:
# Instalar dependências
- name: 'node:18'
  id: 'instalar-dependencias'
  entrypoint: 'npm'
  args: ['ci']

# Configurar Cloud SQL Proxy
- name: 'gcr.io/cloud-builders/wget'
  id: 'configurar-proxy'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Configurando Cloud SQL Proxy..."
      wget https://storage.googleapis.com/cloudsql-proxy/v1.33.2/cloud_sql_proxy.linux.amd64 -O /workspace/cloud_sql_proxy
      chmod +x /workspace/cloud_sql_proxy
      echo "✅ Cloud SQL Proxy configurado com sucesso"

# Executar migração do Prisma
- name: 'node:18'
  id: 'executar-migracao'
  entrypoint: 'bash'
  env:
    - 'DATABASE_URL=${_DATABASE_URL}'
  args:
    - '-c'
    - |
      echo "Iniciando Cloud SQL Proxy..."
      /workspace/cloud_sql_proxy -instances=${_PROJECT_ID}:${_REGION}:pricing=tcp:5432 &

      echo "Aguardando inicialização do proxy..."
      sleep 5

      echo "Executando migração do Prisma..."
      # Modifica a URL para usar localhost
      LOCAL_DB_URL=$(echo $DATABASE_URL | sed 's/\/\/\(.*@\).*:/\/\/\1localhost:/')

      # Gera cliente e aplica migrações
      npx prisma generate
      DATABASE_URL="$LOCAL_DB_URL" npx prisma migrate deploy

      echo "✅ Migração concluída com sucesso!"

# Configurações globais
timeout: '1200s'
substitutions:
  _DATABASE_URL: ""
  _REGION: "southamerica-east1"
  _PROJECT_ID: "truebrands-warehouse"
options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/truebrands-warehouse/secrets/pricing-database-url/versions/latest
    env: '_DATABASE_URL'
