steps:
# Atualizar definição do job de migração
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'atualizar-job-migracao'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'jobs'
    - 'deploy'
    - 'pricing-migration-job'
    - '--region=southamerica-east1'
    - '--image=southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:latest'
    - '--memory=2Gi'
    - '--cpu=2'
    - '--max-retries=3'
    - '--task-timeout=30m'
    - '--set-cloudsql-instances=${PROJECT_ID}:southamerica-east1:pricing'
    - '--service-account=pricing-contract@${PROJECT_ID}.iam.gserviceaccount.com'
    - '--set-secrets=/secrets/.env.local=env_pricing:latest'
    - '--update-env-vars=DOTENV_PATH=/secrets/.env.local,PRISMA_MIGRATE=true'

# Executar migrações
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'executar-migracoes'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'jobs'
    - 'execute'
    - 'pricing-migration-job'
    - '--region=southamerica-east1'
    - '--wait'
  waitFor: ['atualizar-job-migracao']
  timeout: '1800s'  # 30 minutos de timeout

timeout: '2000s'  # Timeout global

options:
  logging: CLOUD_LOGGING_ONLY
