steps:
# Build da imagem
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}', '.']

# Push para o Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}']

# Deploy no Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'pricing'
  - '--image=southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}'
  - '--region=southamerica-east1'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--set-secrets=/secrets/.env.local=env_pricing:latest'
  - '--update-env-vars=DOTENV_PATH=/secrets/.env.local'
  - '--set-cloudsql-instances=${PROJECT_ID}:southamerica-east1:pricing'
  - '--service-account=pricing-contract@${PROJECT_ID}.iam.gserviceaccount.com'
  - '--memory=1Gi'
  - '--cpu=1'

# Recuperar URL do banco do Secret Manager
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud secrets versions access latest --secret=database_url_pricing > /workspace/database_url.txt

# Executar migração do Prisma usando a URL do banco do secret
- name: 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}'
  entrypoint: sh
  args:
  - '-c'
  - 'export DATABASE_URL=$(cat /workspace/database_url.txt) && npx prisma migrate deploy'
  env:
  - 'NODE_ENV=production'

# Verificar se a aplicação está saudável
- name: 'gcr.io/cloud-builders/curl'
  args: ['--retry', '5', '--retry-delay', '10', '-s', '-o', '/dev/null', '-w', '%{http_code}', 'https://pricing-460815276546.southamerica-east1.run.app/api/health']

images:
- 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}'

timeout: '1800s'
