steps:
# Build da imagem
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}', '.']

# Push para o Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}']

# Deploy no Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'pricing'
  - '--image=southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}'
  - '--region=southamerica-east1'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--set-secrets=/secrets/.env.local=env_pricing:latest'
  - '--update-env-vars=DOTENV_PATH=/secrets/.env.local'
  - '--set-cloudsql-instances=${PROJECT_ID}:southamerica-east1:pricing'
  - '--service-account=pricing-contract@${PROJECT_ID}.iam.gserviceaccount.com'
  - '--memory=1Gi'
  - '--cpu=1'

# Executar migração do Prisma diretamente no Cloud Build
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'migrate'
  entrypoint: bash
  args:
    - '-c'
    - |
      echo "Iniciando migração diretamente via Cloud SQL proxy..."
      apt-get update -qq && apt-get install -y -qq gcc python3-dev

      # Instalar o Cloud SQL Proxy
      wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
      chmod +x cloud_sql_proxy

      # Iniciar o Cloud SQL Proxy em background
      mkdir -p /cloudsql
      ./cloud_sql_proxy -instances=${PROJECT_ID}:southamerica-east1:pricing=tcp:5432 &
      PROXY_PID=$!

      # Dar tempo para o proxy iniciar
      sleep 5

      # Instalar Node.js e Prisma
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      npm install -g prisma

      # Instalar dependências do projeto
      cd /workspace
      npm ci

      # Executar migração
      echo "Executando migração do Prisma..."
      DATABASE_URL="postgresql://pricing-system:True%40%23012987@localhost:5432/contract-management" npx prisma migrate deploy

      # Matar o proxy quando terminar
      kill $PROXY_PID

# Verificar se a aplicação está saudável
- name: 'gcr.io/cloud-builders/curl'
  args: ['--retry', '5', '--retry-delay', '10', '-s', '-o', '/dev/null', '-w', '%{http_code}', 'https://pricing-460815276546.southamerica-east1.run.app/api/health']

images:
- 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}'

timeout: '1800s'
