steps:
# Build da imagem
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}', '.']

# Push para o Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}']

# Deploy no Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'pricing'
  - '--image=southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}'
  - '--region=southamerica-east1'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--set-secrets=/secrets/.env.local=env_pricing:latest'
  - '--update-env-vars=DOTENV_PATH=/secrets/.env.local'
  - '--set-cloudsql-instances=${PROJECT_ID}:southamerica-east1:pricing'
  - '--service-account=pricing-contract@${PROJECT_ID}.iam.gserviceaccount.com'
  - '--memory=1Gi'
  - '--cpu=1'

# Executar migração do Prisma diretamente no Cloud Build 
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'migrate'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -e  # Falhar imediatamente se qualquer comando retornar erro

      echo "==== INICIANDO PROCESSO DE MIGRAÇÃO DO BANCO DE DADOS ===="

      # Instalar dependências necessárias
      echo "Instalando dependências..."
      apt-get update -qq && apt-get install -y -qq gcc python3-dev wget curl

      # Instalar o Cloud SQL Proxy
      echo "Baixando e configurando Cloud SQL Proxy..."
      wget -q https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /tmp/cloud_sql_proxy
      chmod +x /tmp/cloud_sql_proxy

      # Criar diretório para o socket do Cloud SQL Proxy
      mkdir -p /cloudsql

      # Iniciar o Cloud SQL Proxy em background sem usar variável
      echo "Iniciando Cloud SQL Proxy..."
      /tmp/cloud_sql_proxy -instances=${PROJECT_ID}:southamerica-east1:pricing=tcp:5432 &

      # Salvar PID diretamente em um arquivo sem usar variável
      echo $! > /tmp/proxy.pid

      # Verificar se o proxy iniciou corretamente
      sleep 5
      if ! ps -p $(cat /tmp/proxy.pid) > /dev/null; then
        echo "ERRO: Cloud SQL Proxy falhou ao iniciar"
        exit 1
      fi

      echo "Cloud SQL Proxy iniciado com sucesso (PID: $(cat /tmp/proxy.pid))"

      # Garantir limpeza no final com uma função que não usa variáveis
      finish() {
        echo "Encerrando Cloud SQL Proxy..."
        kill $(cat /tmp/proxy.pid) || true
        rm -f /tmp/proxy.pid
      }
      trap finish EXIT

      # Instalar Node.js e Prisma
      echo "Configurando ambiente Node.js..."
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs

      echo "Versão do Node.js instalada:"
      node --version

      echo "Instalando Prisma CLI..."
      npm install -g prisma

      # Instalar dependências do projeto
      echo "Instalando dependências do projeto..."
      cd /workspace
      npm ci

      # Acessar o secret para a URL do banco de dados (diretamente, sem variáveis intermediárias)
      echo "Recuperando segredo da URL do banco de dados..."
      gcloud secrets versions access latest --secret="database_url_pricing" > /tmp/db_url

      # Verificar se o arquivo existe e tem conteúdo
      if [ ! -s /tmp/db_url ]; then
        echo "ERRO: Não foi possível recuperar o secret database_url_pricing"
        exit 1
      fi

      # Definir a variável DATABASE_URL explicitamente para o Prisma
      echo "Definindo variável DATABASE_URL para o Prisma..."
      export DATABASE_URL=$(cat /tmp/db_url)

      # Verificar se a variável foi definida corretamente
      echo "Verificando se DATABASE_URL foi definida (exibindo apenas os primeiros caracteres):"
      echo "${DATABASE_URL:0:15}...${DATABASE_URL: -15}" # Mostra apenas o início e final da URL para segurança

      # Verificar conexão com o banco antes de prosseguir
      echo "Verificando conexão com o banco de dados..."
      npx prisma db pull --schema=./prisma/schema.prisma || {
        echo "ERRO: Não foi possível conectar ao banco de dados. Verificando status do proxy:"
        ps -p $(cat /tmp/proxy.pid) || true
        echo "Tentando executar um diagnóstico de rede:"
        apt-get install -y -qq net-tools # Instalar netstat
        netstat -tuln | grep 5432 || true
        exit 1
      }

      # Executar migração usando a variável DATABASE_URL exportada
      echo "Executando migração do Prisma..."
      npx prisma migrate deploy

      migration_status=$?
      if [ $migration_status -eq 0 ]; then
        echo "✅ Migração completada com sucesso"
      else
        echo "❌ Erro na migração do banco de dados"
        exit 1
      fi

      # Limpar arquivos temporários
      rm -f /tmp/db_url

      echo "==== PROCESSO DE MIGRAÇÃO CONCLUÍDO ===="

# Verificar se a aplicação está saudável (com mais detalhes)
- name: 'gcr.io/cloud-builders/curl'
  id: 'health-check'
  entrypoint: bash
  args:
    - '-c'
    - |
      echo "Aguardando aplicação ficar disponível..."
      # Adicionar um tempo para a aplicação iniciar completamente
      sleep 30

      # Verificar o health check com mais detalhes
      echo "Verificando health check da aplicação..."
      curl --retry 5 --retry-delay 10 -s -o /tmp/response.txt -w "%{http_code}" https://pricing-460815276546.southamerica-east1.run.app/api/health > /tmp/http_code

      # Verificar o código HTTP diretamente do arquivo
      if [ "$(cat /tmp/http_code)" = "200" ]; then
        echo "✅ Aplicação está saudável! Status HTTP: $(cat /tmp/http_code)"
        cat /tmp/response.txt
        exit 0
      else
        echo "❌ Falha no health check! Status HTTP: $(cat /tmp/http_code)"
        echo "Resposta recebida:"
        cat /tmp/response.txt
        exit 1
      fi

images:
- 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}'

timeout: '1800s'
