steps:
# Configurar job de migração
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'configurar-job-migracao'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'jobs'
    - 'deploy'
    - 'pricing-migration-job'
    - '--region=southamerica-east1'
    - '--image=southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:latest'
    - '--memory=2Gi'
    - '--cpu=2'
    - '--max-retries=3'
    - '--task-timeout=30m'
    - '--set-cloudsql-instances=${PROJECT_ID}:southamerica-east1:pricing'
    - '--service-account=pricing-contract@${PROJECT_ID}.iam.gserviceaccount.com'
    - '--set-secrets=/secrets/.env.local=env_pricing:latest,DATABASE_URL=database_url_pricing:latest'
    - '--set-env-vars=PRISMA_MIGRATE=true,NODE_OPTIONS=--max-old-space-size=1536,DEBUG=prisma:*,DOTENV_PATH=/secrets/.env.local'

# Executar job de migração
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'executar-migracao'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'jobs'
    - 'execute'
    - 'pricing-migration-job'
    - '--region=southamerica-east1'
    - '--wait'
  waitFor: ['configurar-job-migracao']
  timeout: '1800s'  # 30 minutos de timeout

# Configuração global
timeout: '2400s'  # 40 minutos para todo o build

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Máquina com mais recursos para build eficiente
  dynamic_substitutions: true  # Suporte a substituições dinâmicas
