steps:
# Executar migrações do Prisma no Cloud Run Jobs com passos de diagnóstico
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'executar-migracoes'
  entrypoint: 'gcloud'
  args:
    - 'run'
    - 'jobs'
    - 'deploy'
    - 'pricing-migration-job'
    - '--region=southamerica-east1'
    - '--image=southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:latest'
    - '--memory=2Gi'
    - '--cpu=2'
    - '--max-retries=1'
    - '--task-timeout=30m'
    - '--set-cloudsql-instances=${PROJECT_ID}:southamerica-east1:pricing'
    - '--service-account=pricing-contract@${PROJECT_ID}.iam.gserviceaccount.com'
    - '--set-secrets=/secrets/.env.local=env_pricing:latest,DATABASE_URL=database_url_pricing:8'
    - '--update-env-vars=DOTENV_PATH=/secrets/.env.local,PRISMA_MIGRATE=true,DEBUG=prisma:*,NODE_OPTIONS=--max-old-space-size=1536'
    - '--command=bash'
    - '--args=-c "cd /app && echo \"==== DIAGNÓSTICO AMBIENTE ====\" && pwd && ls -la && echo \"==== VARIÁVEIS AMBIENTE ====\" && printenv | grep -E \"DATABASE_URL|DOTENV_PATH|PRISMA\" && echo \"==== TESTANDO CONEXÃO BD ====\" && if [ -f \"node_modules/.bin/prisma\" ]; then node_modules/.bin/prisma migrate deploy; else npx prisma migrate deploy; fi"'

# Executar o job e capturar logs com melhor tratamento de erro
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'iniciar-migracao'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Iniciando job de migração..."
      job_id=$(gcloud run jobs execute pricing-migration-job --region=southamerica-east1 --format="value(metadata.name)")
      echo "ID do job: $job_id"

      echo "Aguardando execução do job..."
      max_attempts=30
      attempt=1

      while [ $attempt -le $max_attempts ]; do
        echo "Verificando status (tentativa $attempt/$max_attempts)..."

        status=$(gcloud run jobs executions describe $job_id --region=southamerica-east1 --format="value(status)" 2>/dev/null || echo "PENDING")
        echo "Status: $status"

        # Mostrar logs para ajudar no diagnóstico
        echo "Logs recentes:"
        gcloud logging read "resource.type=cloud_run_job AND resource.labels.job_name=pricing-migration-job AND resource.labels.location=southamerica-east1 AND labels.\"run.googleapis.com/execution_name\"=\"$job_id\"" --limit=10 --format="table(timestamp.datetime,severity,textPayload)" 2>/dev/null || echo "Não foi possível obter logs"

        if [ "$status" = "SUCCEEDED" ]; then
          echo "✅ Migração concluída com sucesso!"
          exit 0
        elif [ "$status" = "FAILED" ]; then
          echo "❌ Migração falhou!"

          # Obter mais detalhes sobre o erro
          gcloud run jobs executions describe $job_id --region=southamerica-east1 --format="value(status)" 2>/dev/null || echo "Não foi possível obter detalhes da execução"

          # Exibir logs de erro detalhados
          echo "Logs de erro detalhados:"
          gcloud logging read "resource.type=cloud_run_job AND resource.labels.job_name=pricing-migration-job AND resource.labels.location=southamerica-east1 AND labels.\"run.googleapis.com/execution_name\"=\"$job_id\" AND severity>=ERROR" --limit=50 --format="table(timestamp.datetime,severity,textPayload)"

          # Encerrar com falha mas fornecer informações para diagnóstico
          echo "Para verificar logs completos, acesse:"
          echo "https://console.cloud.google.com/run/jobs/executions/details/southamerica-east1/$job_id/logs?project=${PROJECT_ID}"
          exit 1
        elif [ "$status" = "CANCELLED" ]; then
          echo "❌ Migração foi cancelada."
          exit 1
        fi

        attempt=$((attempt + 1))
        sleep 10
      done

      echo "❌ Timeout ao esperar pela migração."
      exit 1
  waitFor: ['executar-migracoes']
  timeout: '1800s'  # 30 minutos

timeout: '2000s'  # Timeout global

options:
  logging: CLOUD_LOGGING_ONLY
