steps:
# Passo 1: Obter secrets do Secret Manager
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'obter-secrets'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Criar diretório temporário para as configurações
      mkdir -p /workspace/configs

      # Obter DATABASE_URL do Secret Manager
      echo "Obtendo DATABASE_URL do Secret Manager..."
      gcloud secrets versions access latest --secret=database_url_pricing > /workspace/configs/database_url

      # Verificar se conseguimos obter a URL do banco
      if [ ! -s /workspace/configs/database_url ]; then
        echo "❌ Falha ao obter DATABASE_URL do Secret Manager"
        exit 1
      fi

      echo "✅ Secrets obtidos com sucesso"
      echo "DATABASE_URL formato: $(cat /workspace/configs/database_url | sed 's/:[^:]*@/:***@/g')"

# Passo 2: Executar migração diretamente usando a imagem da aplicação
- name: 'docker'
  id: 'executar-migracao'
  args:
    - 'run'
    - '--rm'
    - '-v'
    - '/workspace/configs:/configs'
    - '-e'
    - 'DATABASE_URL=$(cat /configs/database_url)'
    - '-e'
    - 'PRISMA_MIGRATE=true'
    - '-e'
    - 'DEBUG=prisma:*'
    - 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:latest'
    - '/bin/sh'
    - '-c'
    - 'cd /app && echo "== Verificando conexão com banco de dados ==" && echo $DATABASE_URL | sed "s/:[^:]*@/:***@/g" && echo "== Executando migração ==" && npx prisma migrate deploy --schema=prisma/schema.prisma'
  waitFor: ['obter-secrets']

# Configuração global
timeout: '1800s'  # 30 minutos para todo o build

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Máquina com mais recursos para build eficiente
  dynamic_substitutions: true  # Suporte a substituições dinâmicas
