steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'executar-script-migracao'
  entrypoint: bash
  args:
    - '-c'
    - |
      # Garantir permissão de execução
      chmod +x jobs/create-migration-job.sh

      # Executar o script
      ./jobs/create-migration-job.sh

timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
