steps:
# Etapa única: Configurar Cloud SQL Proxy e executar migração
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  id: 'migrar-prisma'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Verificar e encerrar proxies existentes
      echo "Verificando processos existentes do Cloud SQL Proxy..."
      pgrep cloud_sql_proxy && pkill cloud_sql_proxy
      sleep 2

      # Instalação do Cloud SQL Proxy
      echo "Baixando Cloud SQL Proxy..."
      curl -o cloud_sql_proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.6.1/cloud-sql-proxy.linux.amd64
      chmod +x cloud_sql_proxy

      # Criar arquivo de serviço temporário para autenticação
      echo "Configurando autenticação..."
      gcloud auth application-default login --no-launch-browser --quiet

      # Verificar se a porta 5432 está disponível
      if lsof -i :5432 > /dev/null 2>&1; then
        echo "ERRO: Porta 5432 já está em uso!"
        exit 1
      fi

      # Iniciar o Cloud SQL Proxy com a nova sintaxe
      echo "Iniciando Cloud SQL Proxy..."
      ./cloud_sql_proxy "${PROJECT_ID}:southamerica-east1:pricing" --port 5432 &
      echo $! > /tmp/proxy_pid

      # Aguardar o proxy iniciar
      echo "Aguardando inicialização do proxy..."
      sleep 5

      # Verificar se o proxy está escutando
      if ! curl -s http://localhost:5432 > /dev/null; then
        if ! lsof -i :5432 > /dev/null 2>&1; then
          echo "Erro: Cloud SQL Proxy não está escutando na porta 5432"
          kill -9 $(cat /tmp/proxy_pid) || true
          exit 1
        fi
      fi

      echo "Cloud SQL Proxy configurado com sucesso"

      # Executar o Prisma Migrate usando Docker com a rede host
      echo "Executando migração do Prisma..."
      docker run --network=host \
        -e DATABASE_URL="postgresql://${_DB_USER}:${_DB_PASSWORD}@localhost:5432/${_DB_NAME}?schema=public" \
        southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:latest \
        sh -c "cd /app && npx prisma migrate deploy --schema=/app/prisma/schema.prisma"

      # Salvar o resultado
      echo $? > /tmp/result

      # Encerrar o proxy
      echo "Encerrando Cloud SQL Proxy..."
      kill -9 $(cat /tmp/proxy_pid) || true

      # Verificar o resultado
      if [ "$(cat /tmp/result)" = "0" ]; then
        echo "✅ Migração concluída com sucesso"
        exit 0
      else
        echo "❌ Falha na migração"
        exit 1
      fi

# Configuração global
timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
