steps:
  # Remover o job existente primeiro
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'remover-job-existente'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs delete pricing-migration-job --region=southamerica-east1 --quiet || echo "Job não existia"

  # Recriar o job de migração
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'criar-job-migracao'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'pricing-migration-job'
      - '--region=southamerica-east1'
      - '--image=southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:latest'
      - '--memory=4Gi'
      - '--cpu=4'
      - '--max-retries=3'
      - '--task-timeout=30m'
      - '--set-cloudsql-instances=${PROJECT_ID}:southamerica-east1:pricing'
      - '--set-env-vars=NODE_ENV=production,DATABASE_URL=postgresql://${_DB_USER}:${_DB_PASSWORD}@localhost:5432/${_DB_NAME}?schema=public'
      - '--command=sh'
      - '--args=-c,cd /app && npx prisma migrate deploy --schema=/app/prisma/schema.prisma'
    waitFor: ['remover-job-existente']

  # Executar migrações
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'executar-migracoes'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'execute'
      - 'pricing-migration-job'
      - '--region=southamerica-east1'
      - '--wait'
    waitFor: ['criar-job-migracao']
    timeout: '1800s'