steps:
# Usar uma única etapa direta
- name: 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:latest'
  id: 'prisma-migrate'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      # Executar a migração usando diretamente o secret como DATABASE_URL
      echo "Executando migração do Prisma"
      cd /app
      export DATABASE_URL=$(gcloud secrets versions access latest --secret=database_url_pricing)
      npx prisma migrate deploy --schema=/app/prisma/schema.prisma

# Configuração global
timeout: '1800s'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
