steps:
# Build da imagem
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}', '.']

# Push para o Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}']

# Deploy no Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'pricing'
  - '--image=southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}'
  - '--region=southamerica-east1'
  - '--platform=managed'
  - '--allow-unauthenticated'
  - '--set-secrets=/secrets/.env.local=env_pricing:latest'
  - '--update-env-vars=DOTENV_PATH=/secrets/.env.local'
  - '--set-cloudsql-instances=${PROJECT_ID}:southamerica-east1:pricing'
  - '--service-account=pricing-contract@${PROJECT_ID}.iam.gserviceaccount.com'
  - '--memory=1Gi'
  - '--cpu=1'

# Criar job de migração do Prisma
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'jobs'
  - 'create'
  - 'pricing-migrate-${SHORT_SHA}'
  - '--image=southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}'
  - '--set-secrets=/secrets/.env.local=env_pricing:latest'
  - '--update-env-vars=NODE_ENV=production'
  - '--set-cloudsql-instances=${PROJECT_ID}:southamerica-east1:pricing'
  - '--command=sh,-c,echo "[Verificação] Iniciando processo de migração..." && ls -la /secrets/.env.local && echo "[Verificação] Carregando variáveis de ambiente..." && set -a && source /secrets/.env.local && set +a && echo "[Verificação] Variáveis carregadas" && echo "[Verificação] DATABASE_URL=$DATABASE_URL" && echo "[Verificação] Executando migração..." && npx prisma migrate deploy'
  - '--region=southamerica-east1'
  - '--tasks=1'
  - '--memory=512Mi'
  - '--cpu=1'
  - '--max-retries=3'
  - '--service-account=pricing-contract@${PROJECT_ID}.iam.gserviceaccount.com'
  - '--timeout=600s'
  - '--task-timeout=600s'

# Executar job de migração
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'jobs'
  - 'execute'
  - 'pricing-migrate-${SHORT_SHA}'
  - '--region=southamerica-east1'
  - '--wait'

# Verificar se a aplicação está saudável
- name: 'gcr.io/cloud-builders/curl'
  args: ['--retry', '5', '--retry-delay', '10', '-s', '-o', '/dev/null', '-w', '%{http_code}', 'https://pricing-460815276546.southamerica-east1.run.app/api/health']

images:
- 'southamerica-east1-docker.pkg.dev/${PROJECT_ID}/pricing-repo/pricing:${SHORT_SHA}'

timeout: '1800s'
