version: '3.8'

services:
  cloud-sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
    container_name: contract_management_proxy
    command:
      - "--address=0.0.0.0"
      - "--port=5432"
      - "--credentials-file=/secrets/key.json"
      - "truebrands-warehouse:southamerica-east1:pricing"
    volumes:
      - ./key.json:/secrets/key.json:ro
    networks:
      - contract_management_network
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    container_name: contract_management_redis
    networks:
      - contract_management_network
    ports:
      - '6379:6379'
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contract_management_api
    depends_on:
      - redis
      - cloud-sql-proxy
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://pricing-system:True%40%23012987@cloud-sql-proxy:5432/contract-management?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''
    networks:
      - contract_management_network
    command: sh -c "npx prisma db push --accept-data-loss && node dist/main"
    restart: unless-stopped

networks:
  contract_management_network:
    driver: bridge
