export enum EStatusChangeReason {
    INITIAL_CREATION = 'INITIAL_CREATION',
    SENT_TO_SIGNATURE = 'SENT_TO_SIGNATURE',
    SIGNED = 'SIGNED',
    EXPIRED = 'EXPIRED',
    CANCELLED = 'CANCELLED',
    MANUAL_CANCELLATION = 'MANUAL_CANCELLATION',
}
